### ISSUE TITLE
All Frontmatter deleted in Expert Mode

### ISSUE THREAD

**Issue by cniweb** [getgrav/grav-plugin-admin#1354]
With the Grav v1.3.10 and Admin v1.6.7, I have the follwing problem:

Whenever I save a page in Export mode, all Frontmatter (including title etc.) is deleted and replaced with

`media_order: ''`

Has been reported before: #1252

**Comment by RobLui** [comment]
I've had the same issue when i turned edit mode to expert in the admin , when you turn it off and just go to the page itself and edit in expert mode over there, it works just fine for me, might be the same thing for you

**Comment by cniweb** [comment]
Thanks for the tip, it helps. But that's just a workaround.

**Comment by RobLui** [comment]
Yeah, it needs a fixo defo :)

**Comment by rhukster** [comment]
To confirm, this only happens when the 'default' mode as set in the admin options is set to "expert"? And it works fine when you leave the normal mode, but switch to expert on the page?

**Comment by RobLui** [comment]
Confirm - in my case @rhukster

**Comment by cniweb** [comment]
This only happens when the default mode in Admin Options is set to "Expert".

**Comment by rhukster** [comment]
Can you please test with Grav 1.4 RC with Admin 1.7 RC, because I can't replicate it there. I think a bug I fixed in handling frontmatter might of fixed this too.

**Comment by rhukster** [comment]
![edit_frontmatter-delete___grav](https://user-images.githubusercontent.com/1084697/37110836-492a5026-21fb-11e8-8bcc-faf66320ee41.jpg)

Screenshot to show a save on a test page.

**Comment by RobLui** [comment]
testing atm

**Comment by RobLui** [comment]
Before:
![Before](http://share-my-bugs.robbertluit.be/uploads/50739.png "Before")

After:
![After](http://share-my-bugs.robbertluit.be/uploads/78370.png "After")

Issue still persists

Admin version:
| 230 | Admin Panel | admin | v1.7.0-rc.3   | installed |

**Comment by rhukster** [comment]
@RobLui can you zip up your Grav site and let me download it? I think this might be related to a plugin or at least a configuration setting.

**Comment by rhukster** [comment]
Also what page type is this? Does it happen for all including `default` ?

**Comment by mpduarte** [comment]
I've been having the same issue, also having the same issue after upgrading to the RC releases. Use case is occurring on a template other than default. Just tested using default, same thing occurs.

**Comment by mpduarte** [comment]
@rhukster I can give you a zip copy of my site, as long as you don't need anything in pages or users. Would that suffice for troubleshooting?

**Comment by RobLui** [comment]
Can you check Slack :) ? Pm'ed you @rhukster

**Comment by rhukster** [comment]
Found it and fixed.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/c15fe282dae4a37c59856a283fbdd00fbaa54ff0

**Comment by RobLui** [comment]
AWESOME :-)

**Comment by mpduarte** [comment]
Thanks @rhukster , patched our deployment with the change, and everything is working great over here. Appreciate it!

**Comment by cniweb** [comment]
Thanks @rhukster 👍
